#Nishant
openapi: 3.0.1

paths:
  /books:
    get:
      summary: geapt all books
      responses:
        200:
          description: an array of books
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    
    post:
      summary: add books
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/BookBody'
      responses:
        200:
          description: "Book created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          
          
  /books/{id}:
    put:
      summary: update books
      parameters:
        - in: path
          name: isbn
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Book'
      responses:
        200:
          description: "Book updated successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          
        
      
components:
  schemas:
    BookBody:
      properties:
        title:
          type: string
          example: sea tides
        author:
          type: string
          example: alexandar
        isbn:
          type: string
          example: 1232
    Book:
      allOf: 
        - $ref: "#/components/schemas/BookBody"
        - type: object
          properties:
            id:
              type: string
              example: 24524624gr44w4

  